defaults: &defaults
    parallelism: 1
    working_directory: ~/workspace
    docker:
      - image: 421990735784.dkr.ecr.us-east-1.amazonaws.com/ci-build-environment:golang-1.16
        aws_auth:
          aws_access_key_id: $AWS_ACCESS_KEY_ID
          aws_secret_access_key: $AWS_SECRET_ACCESS_KEY
version: 2
jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Install aws cli
          command: sudo apt-get install -y awscli
      - run: export VERSION=$(git describe --always --long --dirty)
      - run: GOOS=linux GOARCH=amd64 go build -o global_docker_compose -v -ldflags="-X main.version=${VERSION}" cmd/gdc/main.go

      - persist_to_workspace:
          # Must be an absolute path, or relative path from working_directory
          root: ~/workspace
          # Must be relative path from root
          paths:
            - .
  lint:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/workspace
      - run: export PATH="$PATH:/go/bin"
      - run: go get -u golang.org/x/lint/golint
      - run: golint -set_exit_status $(go list ./... | grep -v /vendor/)

  deploy-to-prod:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/workspace
      - run: git reset --hard
      - run: curl -sL https://git.io/goreleaser | bash    

workflows:
  version: 2
  build-test-and-deploy:
    jobs:
      - build
      - lint:
          requires:
            - build
      - deploy-to-prod:
          requires:
            - lint
          filters:
            tags:
              only: /v[0-9]+(\.[0-9]+)*(-.*)*/
